#!/bin/bash

if [ ! -e "$HOME"/.config/nvim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.config/nvim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
nvim -u "$HOME"/.config/nvim/bundles.vim +PlugInstall +PlugClean! +qa

if [ ! -e "$HOME"/.asdf ]; then
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf
  pushd ~/.asdf
  git checkout "$(git describe --abbrev=0 --tags)"
  popd
fi

if [ ! -e "$HOME"/.asdf/plugins/elixir ]; then
  asdf plugin-add elixir https://github.com/asdf-vm/asdf-elixir.git
fi

if [ ! -e "$HOME"/.asdf/plugins/erlang ]; then
  asdf plugin-add erlang https://github.com/asdf-vm/asdf-erlang.git
fi

# detect old OS X broken /etc/zshenv and suggest rename
if grep -qw path_helper /etc/zshenv 2>/dev/null; then
  if [ -t 2 ]; then
    fg_red=$'\e[31m'
    fg_bold_white=$'\e[1;37m'
    reset_color=$'\e[m'
  else
    fg_red=""
    fg_bold_white=""
    reset_color=""
  fi

  # resolve BASH_SOURCE to absolute path
  bash_source="$BASH_SOURCE"
  if [[ $bash_source == */* ]]; then
    pushd "${bash_source%/*}" >/dev/null
    bash_source="${PWD}/${bash_source##*/}"
    popd >/dev/null
  fi

  cat <<MSG >&2
${fg_red}Warning:${reset_color} \`/etc/zshenv' configuration file on your system may cause unexpected
PATH changes on subsequent invocations of the zsh shell. The solution is to
rename the file to \`zprofile':
  ${fg_bold_white}sudo mv /etc/{zshenv,zprofile}${reset_color}

(called from ${bash_source}:${LINENO})

MSG
fi
